### ISSUE TITLE
Add monitoring 

### ISSUE THREAD

**Issue by Thykof** [peterjah/massa-core-docker#2]
We want to be able to monitor the node.

This could be done by adding Prometheus and Grafana.

Bellow is a configuration proposal:

`docker-compose.yml`:

```yml
version: '3.7'

services:
  prometheus-node-exporter:
    image: prom/node-exporter
    container_name: prometheus-node-exporter
    ports:
      - 9100:9100


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

```

`prometheus.yml`:

```yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['prometheus-node-exporter:9100']
```

`grafana.ini`:

```ini
[server]
http_port = 3000

[security]
admin_user = admin
admin_password = admin123

[database]
type = sqlite3
path = grafana.db

[session]
provider = memory

[analytics]
check_for_updates = true
```

`datasource.yml`:

```yml
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
```
